version: '3'
services:
  app:
    build: https://github.com/Lakshmi-Shravani-K-24/Connectors.git
    ports:
      - "3000:3000"
      - "3003:3003"
    environment:
      MONGODB_URL: mongodb://mongo:27017/ChargeStationDB
    depends_on:
      - mongo
    networks:
      - connectors-network

  mongo:
    image: mongo:latest
    ports:
      - "49152:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - connectors-network

  estimate:
    build: https://github.com/Lakshmi-Shravani-K-24/EstimatedServerOfConnectors.git
    ports:
      - "3001:3001"
    networks:
      - connectors-network

networks:
  connectors-network:
    driver: bridge

volumes:
  mongo-data:
